version: '3'
services:
  app:
    restart: always
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/data
    environment:
      FLASK_ENV: development
    networks:
      - app-network
  website:
    image: php:apache
    volumes:
      - ./website:/var/www/html
    depends_on:
      - app  
    ports:
      - "5001:5000"
    networks:
      - app-network
volumes:
  db-data:
networks:
  app-network:
    driver: bridge
